Add Publish content to Crafter CLI develop -Ticket 843
craftercms/cli pull request #19
Opened 2024-05-14 19:03 UTC by Euquimides

Added Publish Content Option to Crafter CLI, following ticket:
https://github.com/craftersoftware/craftercms/issues/843

2024-05-14 19:08 UTC, Euquimides commented on src/main/groovy/org/craftercms/cli/commands/site/PublishContent.groovy
> +        def path = '/studio/api/2/workflow/publish.json'
Notice that this endpoint will be deprecated in the future based on: https://github.com/craftercms/studio/pull/3544/files#diff-855ee91a131d9de0f962d9f7c1631e86abf9712d9347bcdeb32b6a265f2bfbbdR6624

I will change this once the new APIs are implemented.

2024-05-14 19:39 UTC, yacdaniel approved these changes

2024-05-15 12:36 UTC, sumerjabri commented on src/main/groovy/org/craftercms/cli/commands/site/PublishContent.groovy
> +            println "The selected content has been published to ${publishingTarget}"
submitted to be published

2024-05-15 12:37 UTC, sumerjabri commented on README.md
> +Also, you are able to publish an item to live or staging (staging must be enabled first before using that target):
You can publish content to the Live or Staging targets (Staging must be enabled to publish to it):

2024-05-15 12:38 UTC, sumerjabri commented on README.md
> +To publish various items to live or staging, you can use the following command (be wary of the quotes and spaces):
To publish multiple items, separate them by comma.

2024-05-15 12:39 UTC, sumerjabri requested changes
See my notes

2024-05-15 15:19 UTC, sumerjabri approved these changes

2024-05-15 15:19 UTC, merged